### ISSUE TITLE
 randomly react other user's swearing.

### ISSUE THREAD

**Issue by chitacan** [RedRibbon/redribbot#28]
ex

```
user  | 아우 씨발...
hubot | 썅 너 뭐라고 했냐? 씨발?
```

**Comment by imazine** [comment]
Separate response list object to file(ex>swearDictionary.json) for contribution easier.
It can makes crazy contribution.:D

**Comment by chitacan** [comment]
we need @yunjungbu 's :tongue:  for this job.

**Comment by coma333ryu** [comment]
:+1:

**Comment by chitacan** [comment]
:eyes: https://github.com/RedRibbon/redribbot/blob/master/scripts/auto-react.coffee
